sudo: required
services: 
    - docker
cache: apt
language: cpp
addons:
  apt:
    packages:
      - cppcheck
      - libudev-dev
matrix:
  include:
  - os: linux
    compiler: clang
    env: QMAKESPEC=linux-clang
before_install:
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install qt5-default libqt5serialport5-dev
- qmake -v
script:
- qmake
- make -j4
after_script:
- cppcheck --enable=all -q `git ls-files *.cpp *h`
