sudo: required
dist: trusty
cache: apt
language: cpp
addons:
  apt:
    packages:
    - libudev-dev
    - qt5-default
    - libqt5serialport5-dev
matrix:
  include:
  - os: linux
    compiler: g++
  - os: linux
    compiler: clang
    env: QMAKESPEC=linux-clang
  - os: osx
    compiler: clang
    env: PATH=/Users/travis/local/bin:$PATH
install: "./.travis/install.sh"
script: "./.travis/script.sh"
deploy:
  provider: releases
  api_key:
    secure: P8fXvlfyRvFaump8GFGmbtVjiPulWaA7EaUW2+EfirN+jb9vA1T0g23Lzh5rj0ZyQjXtyPIH1dyLynCLFqigrq8yhEAbJfkeuqsDbdH6jnKSxl/cRDDtmpvQQKAbKdInNy4OE/8Pk0wu+qxbOYWwkw2EbReEORSkO98DpM7ygyk=
  file_glob: true
  file: propellermanager-*.tgz
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerManager
    tags: true
    all_branches: true
