language: cpp
os:
  - linux
  - osx
matrix:
  include:
  - compiler: gcc
  - compiler: clang
    env: QMAKESPEC=linux-clang
  exclude:
  - os: osx
    compiler: clang

before_install:
- sudo add-apt-repository "deb http://cz.archive.ubuntu.com/ubuntu utopic main"
- sudo apt-get update
- sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools qtchooser qttools5-dev qtbase5-dev libgles2-mesa-dev libqt5gui5 libqt5serialport5-dev libqt5printsupport5 libqt5widgets5 libgles2-mesa libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libegl1-mesa-dev libpango-1.0-0
- sudo apt-get install zlib1g-dev libudev-dev cppcheck
- qmake -v
script:
- qmake
- make -j4
after_script:
- cppcheck --enable=all -q `git ls-files *.cpp *h`
